site_name: Hacking Technicolor Gateways
repo_url: https://github.com/kevdagoat/hack-technicolor/

theme:
    name: material
    
markdown_extensions:
    - toc:
        permalink:
    - admonition
    - def_list
    - nl2br

extra_css:
    - css/extra.css
