site_name: Hacking Technicolor Gateways
repo_url: https://github.com/kevdagoat/hack-technicolor/

theme:
    name: material
    
markdown_extensions:
    - toc:
        permalink:
    - admonition
    - def_list
    - nl2br

extra_css:
    - css/extra.css
    
plugins:
    - search

nav:
    - 'Home': 'index.md'
    - 'Firmware Repository': 'Repository.md'
    - 'Hack Type 1&2': 'Hack Type 1&2.md'
    - 'Hardening Root Access': 'Hardening.md'
    - 'Unlock Functionality': 'Unlock.md'
    - 'Recovery': 'Recovery.md'
    - 'Resources': 'Resources.md'
    - 'Safe Firmware Upgrade': 'Upgrade.md'